# Generated by Django 4.1 on 2023-12-07 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/img/beneficios/')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('areaAcademica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('codigo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='core/img/totems')),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficio')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigosecc', models.CharField(max_length=12, unique=True)),
                ('alumnos', models.ManyToManyField(blank=True, to='core.alumno')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
            ],
        ),
    ]
