# Generated by Django 4.1 on 2023-12-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_totem_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigosecc',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
