# Generated by Django 4.1 on 2023-12-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_curso_codigosecc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='imagen',
            field=models.ImageField(upload_to='static/core/img/totems/'),
        ),
    ]
